### PR TITLE
Use poetry to manage package and make it easy to publish to PyPI

### PR DESCRIPTION
**Pull request by peinan**
This library is exactly what I exactly wanted and exactly what I was trying to create. The design philosophy and motivation are very close to mine. I hope I can help in some small way.

#### Added files:
- `pyproject.toml`: a config file for poetry
- `poetry.lock`: auto-generated lock file by execute `poetry lock`
- `tox.ini`: a config file for tests and measuring code coverage

#### Usage

```bash
# 1. Run tests using tox through poetry env
$ poetry run tox

# 2. (Optional) Run codecov
$ poetry run codecov -t ${CODECOV_TOKEN}

# 3. (Optional) Publish to PyPI
$ poetry publish --build -u ${PYPI_USERNAME} -p ${PYPI_PASSWORD}
```
<details><summary><strong>Execution history</strong></summary>

```bash
$ poetry run tox
py38 installed: appdirs==1.4.4,attrs==20.2.0,CacheControl==0.12.6,cachy==0.3.0,certifi==2020.6.20,chardet==3.0.4,-e git+git@github.com:peinan/chika.git@cd93439c059dbe264bad5c2760a71c6ae63c2287#egg=chika,cleo==0.7.6,clikit==0.4.3,codecov==2.1.9,coverage==5.3,distlib==0.3.1,filelock==3.0.12,html5lib==1.1,idna==2.10,iniconfig==1.0.1,jsonschema==3.2.0,keyring==20.0.1,lockfile==0.12.2,more-itertools==8.5.0,msgpack==1.0.0,packaging==20.4,pastel==0.2.1,pexpect==4.8.0,pkginfo==1.5.0.1,pluggy==0.13.1,poetry==1.0.10,ptyprocess==0.6.0,py==1.9.0,pylev==1.3.0,pyparsing==2.4.7,pyrsistent==0.14.11,pytest==6.0.2,pytest-cov==2.10.1,PyYAML==5.3.1,requests==2.24.0,requests-toolbelt==0.8.0,shellingham==1.3.2,six==1.15.0,toml==0.10.1,tomlkit==0.5.11,tox==3.20.0,urllib3==1.25.10,virtualenv==20.0.31,webencodings==0.5.1
py38 run-test-pre: PYTHONHASHSEED='1062298837'
py38 run-test: commands[0] | poetry install
Installing dependencies from lock file

No dependencies to install or update

  - Installing chika (0.1.0)
py38 run-test: commands[1] | poetry run pytest --cov=chika tests
============================================ test session starts =============================================
platform darwin -- Python 3.8.5, pytest-6.0.2, py-1.9.0, pluggy-0.13.1
cachedir: .tox/py38/.pytest_cache
rootdir: /path/to/chika
plugins: cov-2.10.1
collected 13 items

tests/test_config.py ..                                                                                [ 15%]
tests/test_io.py .                                                                                     [ 23%]
tests/test_main.py ..                                                                                  [ 38%]
tests/test_parser.py ........                                                                          [100%]

---------- coverage: platform darwin, python 3.8.5-final-0 -----------
Name                Stmts   Miss  Cover
---------------------------------------
chika/__init__.py       1      0   100%
chika/chika.py        221     28    87%
---------------------------------------
TOTAL                 222     28    87%


============================================= 13 passed in 0.16s =============================================
__________________________________________________ summary ___________________________________________________
  py38: commands succeeded
  congratulations :)
```

</details>

### Modified class name `Config` to `BaseConfig` in README.md

In README.md, `BaseConfig` was used in the explanation:

> Then, wrap the main function with `chika.main(BaseConfig)`,

but `Config` was used in the code example:

```python
@chika.main(Config)
def main(cfg: Config):
```

So I unified them to use `BaseConfig`.

### CODE REVIEW

**Comment by moskomule** [comment]
Thank you for your contribution.

* `BaseConfig`: Thanks, I noticed but didn't fix it.
* `poetry`: I'm not familiar with poetry, so I have some questions.
  - Does it work with `conda`? For PyTorch, I usually use conda, and I don't want to change this for while.
  - Isn't `poetry.lock` for your environement? It seems to include a lot of unnecessary dependencies of `chika`.

**Comment by peinan** [comment]
Thank you for your response!

- > `BaseConfig`: Thanks, I noticed but didn't fix it.
  - Oh, is there any reason for this ?
- > Does it work with conda ?
  - Sorry, I'm not familiar with conda...As far as I searched, it seems work with each other, but maybe not a good way due to the mess of paths.
- > Isn't `poetry.lock` for your environement? It seems to include a lot of unnecessary dependencies of chika.
  - I added some packages such as `pytest`, `tox`, and so on to `pyproject.toml`'s `dev-dependency` for testing. Poetry locks all the dependencies of the required packages. Maybe that's the reason why you feel the required packages are more than the original. Poetry can show the dependency tree; I attach the result image just in case.

Overall, I'm start thinking that this PR is not a good idea, that affect the environment too much. Do you mind if I withdraw this PR ?

ss 2020-09-24 15 26 27

**Comment by moskomule** [comment]
* `BasicConfig`: Sorry, I meant I forgot fixing it. 
* `poetry`: I will also try in my environment if it works. Let's discuss it after that.

I'm happy to have your PR and don't want you to withdraw it.

**Comment by moskomule** [comment]
Hi, @peinan! I really appreciate your PR, but because of my concern about poetry, I decided to employ another way. Now, chika is available on pypi, i.e., you can install it by `pip install chika`.
Again, thank you for your PR, and if you have any feature requests or improvements, don't hesitate to raise issues or send PRs.

**Pull request closed without merging**
